@startuml

note as Requerimientos
    Requerimientos: 
    - Crear un reproductor de audio
    - Poder elegir el fichero a reproducir
    - Poder pausar y reanudar la reproducción
    - Poder reproducir una lista de audios
end note 

note as Consideraciones
    Consideraciones:
    - La clase FileSelector presenta una ventana para elegir el fichero
end note

note as Tradeoffs
    Tradeoffs:
    - La clase Chunk es dependiente del sistema, es posible que el tamaño mínimo de buffer varíe
end note

class Player {
    play(bytes: [Byte])
    --
    - Envía stream de bytes al sistema de audio
}

class Playback {
    init(chunks: [Chunk])
    play()
    pause()
    --
    - Guarda la posición de reproducción
    - Monitoriza el estado
    - Envía streams de bytes al reproductor dependiendo del estado
    - Notifica cuando se han reproducido todos los chunks
}

class FileSelector {
    - Permite al usuario elegir un fichero
}

class FileMapper {
    - Convierte un fichero en un array de chunks reproducibles
}

class App {
    - Inicializa los sistemas necesarios
}

class Chunk {
    var bytes: [Byte]
    --
    init(bytes: [Byte])
    --
    - Almacena un array de bytes que se puede enviar al reproductor
}

class ViewPresenter {
    - Presenta las vistas y controles
    - Responde a los eventos de los controles
}

class Playlist {
    addFile(file: File)
    removeFile(file: File)
    obtainFileToPlay() -> File
    --
    - Almacena un listado de ficheros
    - Permite gestionar los ficheros de la lista
    - Guarda el fichero actual que se está reproduciendo
    - Obtiene el siguiente fichero a reproducir
}

class PlaylistPlayer {
    play()
    pause()
    --
    - Obtiene el fichero a reproducir desde la playlist
    - Convierte el fichero al formato reproducible
    - Gestiona la reproducción de cada fichero
    - Propaga eventos relacionados con la reproducción - play y pause
    - Monitoriza cuando un fichero ha terminado de reproducirse
}

App .. ViewPresenter
App .. Playlist
App .. PlaylistPlayer
Playback .. Player
Playback .. Chunk
FileMapper .. Chunk
ViewPresenter .. Playlist
ViewPresenter .. FileSelector
ViewPresenter .. PlaylistPlayer
PlaylistPlayer .. Playlist
PlaylistPlayer .. FileMapper
PlaylistPlayer .. Playback

App .. Requerimientos
FileSelector .. Consideraciones
Chunk .. Tradeoffs

@enduml